### ISSUE TITLE
XssSaxFilter, XssFilter에서 사용하는 xml 파일도 만들어줘야 하나요?

### ISSUE THREAD

**Issue by TaeSeong** [naver/lucy-xss-servlet-filter#1]
안녕하세요.
지난번 스프링 캠프에서 servlet filter가 곧 나올거라 하셨었는데 지금에서야 보고 적용하고 있는 중에 궁금한점이 있어 문의드립니다.

lucy-xss-servlet-filter-rule.xml에서

       
       <defender>
           <name>xssSaxFilterDefender</name>
           <class>com.navercorp.lucy.security.xss.servletfilter.defender.XssSaxFilterDefender</class>
           <init-param>
               <param-value>lucy-xss-sax.xml</param-value>   
               <param-value>true</param-value>        
           </init-param>
       </defender>

       
       <defender>
           <name>xssFilterDefender</name>
           <class>com.navercorp.lucy.security.xss.servletfilter.defender.XssFilterDefender</class>
           <init-param>
               <param-value>lucy-xss.xml</param-value>    
               <param-value>true</param-value>         
           </init-param>
       </defender>

위와 같이 XSS Filter를 등록하는 부분이 있는데 여기서 사용하는 lucy-xss-sax.xml, lucy-xss.xml을 만들어주어야 하는건가요??
따로 생성해주지 않아도 테스트해보니 정상적으로 필터링하는걸 확인했지만 혹시나 해야하는건지..
문의드립니다.

**Comment by leeplay** [comment]
사용하시는 필터에 따라 다른데요, 사용하시는 필터가 무엇인지요 ??

간단히 설명을 드리면 
사용하시려는 필터가 XssPreventer 뿐이라면 추가적인 설정은 필요없습니다. ^^
다른 필터인 XssSaxFilter, XssFilter를 사용하시려면 필요에 따라 설정이 필요한데요 
(설정하지 않으시면 단순 html태그 escaping만 하는데 이 경우라면 이 필터를 사용하실 필요는 없으세요)

설정이 필요한 경우는 크게 두 가지가 있는데요 
- html태그를 그대로 유지한채 공격 요소만 제거해야 할 경우 
- 특정 태그나 속성에 이벤트 리스너를 등록해야 할 경우 

위에 해당이 되시면 기본예제를(https://github.com/naver/lucy-xss-filter/blob/master/src/test/resources/lucy-xss-sax.xml) 한번 봐주세요

좋은 하루 되세요

**Comment by TaeSeong** [comment]
바쁘실텐데 자세한 답변 감사합니다!
좋은 하루 되세요 :D
