### ISSUE TITLE
특정 URL에 필터링을 해제하고 싶은데..

### ISSUE THREAD

**Issue by TaeSeong** [naver/lucy-xss-servlet-filter#11]
<url-rule-set>
       
       <url-rule>
           <url disable="true">/manual/*</url>
       </url-rule>
    </url-rule-set>

/manual/ 하위에 있는 모든 경로의 url에는 필터링을 하고 싶지 않은데

위와 같이 설정하니 필터링 해제가 되지 않네요

어떻게 처리해야될까요??

**Comment by leeplay** [comment]
안녕하세요 
먼저 문의하신 와일드 카드 지정 기능은 없습니다. 

구현방법은 심플한데 그 기능을 넣지 않은 이유는 
와일드카드 표현을 사용하고 보니 결국 어떤 url에서 공격이 발생하는지 인지를 못 하게되고 담당자가 변경되면서 관리가 되지않아 XSS 공격에 시달리는 사례가 여러 번 발생하였습니다. 
그래서 네이버 내부에서는 필터링하지 않는 url은 전부 파일에 명시하자는 결론을 내렸습니다.
(아래내용은 문의하신 건으로 내부에서 주고받은 의견입니다.)

```
말씀하신데로 도입에 조심스럽다는 입장입니다.
나름 자신들의 서비스에 대한 위험성을 책임져야하므로 설마 전체를 지정하는 경우는 없을것 같기는합니다.
그래도 범위를 지나치게 넓게 지정해서 통제되지 못한 구멍이 생길 위험성이 있습니다.

어느 URL이 제외대상인지 와일드카드 없이 명시하는게 아래와 같은 장점이 있다고 생각합니다..

의도하지 않게 필터링에서 URL이 제외될 가능성을 줄임
새로운 URL을 추가할때 이 URL이 필터링 대상에 포함될지 안 될지를 고민하고, 뺼 경우 이를 의식하게 됨. 의식하지 않고 추가했을때는 디폴트로 escape가 되는게 바람직한것 같습니다.
다만, 특정 URL제외기능에서 search.nhn 을 명시하면 search.nhn?query=kimho 같이, 쿼리스트링 부분은 상관없이 대상에 포함되는거겠죠? 그렇다고 하면, 제 생각에는 큰 불편함은 없을것 갇고, 어느 정도의 불편함은 보안성을 높이는데 투자하는 의미로 생각할만합니다. 이미 특정 URL전체 지정기능으로 어느정도 편의성을 높이기도 했는데, 더 나아갈지는 조심스럽게 결정해야곘습니다.
```
현재는 url을 전부 명시하던지, 체크로직을 수정하던지 둘 중에 하나를 선택하셔야 할 거 같습니다.

(https://github.com/naver/lucy-xss-servlet-filter/blob/master/src/main/java/com/navercorp/lucy/security/xss/servletfilter/XssEscapeFilterConfig.java)

![2016-07-29 16 21 09](https://cloud.githubusercontent.com/assets/7857613/17240780/80d6fc16-55a8-11e6-9de0-7a0d0e9e1052.png)

저기서 url의 필터링 여부를 판단할 때 Java Regex로 비교하면 될 거 같습니다. 
(화이팅입니다...)

**Comment by TaeSeong** [comment]
답변 감사드립니다.
말씀하신대로 필터링하지 않는 url은 모두 명시하고 관리하는게 좋은 방법인것 같습니다.
꼭 필요하다면 알려주신대구 구현해서 사용하도록 하겠습니다.
자세한  답변 감사드립니다.. 즐거운 주말 되세요. ^^
