### ISSUE TITLE
XssPreventerDefender에서 특수문자 제외할 수 없나요?

### ISSUE THREAD

**Issue by nocode2k** [naver/lucy-xss-servlet-filter#14]
안녕하세요.

Lucy xss filter  : 1.6.3
Lucy xss servlet : 2.0.0 을 사용하고 있는 개발자입니다.

Filtering되는 데이터 중에서 &를 제외해야 하는 critical한 issue가 발생하여 문의드립니다.
설정만으로 제외Rule을 적용할 수 있는 방법이 있을까요?
아니면 XssPreventerDefender class 대신에 별도의 Defender class를 구현해서 설정해줘야 할까요?

확인부탁드립니다.

**Comment by leeplay** [comment]
안녕하세요 

먼저 일단 일부문자를 필터링을 제외하는 방법은 설정으론 방법이 없네요 ;
& 이 데이터는 StringEscapeUtils.escapeHtml4(dirty) 여기서(apache library) 필터링이 되고 있어서 좀 더 애매합니다.;

![2016-11-24 17 29 41](https://cloud.githubusercontent.com/assets/7857613/20591383/99514df8-b26b-11e6-8c2f-9c41e4c6ffc7.png)

현재 가능한 해결방법은 말씀하신 두 가지인 거 같습니다.

- 먼저 설정을 좀 우회시켜볼려면 & 이 데이터를 전송하는 파라미터가 한정되어 있다면 그 파라미터에는 escape를 하지않도록 설정파일에 선언하시고 비즈니스 로직에서 자체 필터링을 하는 방법이 가장 괜찮은 거 같습니다.

- 위의 안이 불가하시면 소스코드를 수정해야 할 거 같은데요, 필터링 하시는 문자열들이 고정되어 있고 정의되어 있다면 아예 해당 소스에 Pattern.comopile 부분에 필터링 대상 문자열들을 전부 지정하시고 escape 메소드에서 StringEscapeUtils.escapeHtml4를 제거 후 자체 for문을 수행하도록 수정하셔야 할 거 같습니다. (메이븐 프로젝트라 pom.xml만 import하시고 수정 후 컴파일 된 결과물은 사용하면 되서..  가능은 하긴한데 번거로우실 거 같네요 ;)

**Comment by nocode2k** [comment]
감사합니다. 말씀해주신 내용으로 검토해서 적용해봐야겠네요.
즐거운 하루 되세요.

**Comment by leeplay** [comment]
앗 중요한 사항을 빠뜨렸네요, 위의 소스코드는 lucy-xss-filter 프로젝트의 XssPreventer 클래스입니다. 
(질문만으로 내공이 느껴지셔서 더 디테일한 설명은 실례가 될까 하지 않겠습니다. ^^ 좋은 하루 되세요)
