### ISSUE TITLE
url-rule 에 url 체크시 문제점

### ISSUE THREAD

**Issue by bamtolee002** [naver/lucy-xss-servlet-filter#17]
url 체크시 contextPath까지 포함되어있어서, contextPath변경시 url-rule 까지 변경해야하는 번거로움이 있습니다.

하여
XssEscapeServletFilterWrapper 에서 
this.path = this.path.replace(((HttpServletRequest)request).getContextPath(),"");
를 추가하는게 어떨까 합니다.

**Comment by antop-dev** [comment]
혼자 수정해서 쓰다가 공유합니다.
https://github.com/antop-dev/lucy-xss-servlet-filter

**Comment by leeplay** [comment]
@bamtolee002 

주신 의견 확인해보겠습니다. (풀리퀘 보내주셔도 감사합니다. _ _)

**Comment by kakasleki** [comment]
maven 에는 최종 소스가 업데이트 되어 있지 않은거 같네요. 해당부분 확인부탁드립니다.
