### ISSUE TITLE
lucy-xss-servlet-filter 한글이 깨지는 문제가 발생했습니다 ㅠㅠ 

### ISSUE THREAD

**Issue by yangbongsoo** [naver/lucy-xss-servlet-filter#2]
안녕하세요 제가 웹 홈페이지를 제작하면서 XSS 공격을 막기 위해 네이버 오픈소스인 lucy-xss-servlet-filter를 적용하려고 하는데 한글이 깨지는 문제가 발생해서 메일을 보내게 되었습니다. 
lucy-xss-servlet-filter 붙이기 전엔 한글이 정상적으로 입력되는거까지 확인했구요. 

제가 취한 행동으로는 
1. maven 설정(1.6.3이상입니다)
![lucy 3](https://cloud.githubusercontent.com/assets/7060510/8589861/b6689c1e-2655-11e5-8a32-dae8688da62f.PNG)

2. /resourse에 lucy-xss-servlet-filter-rule.xml 넣기
![lucy 1](https://cloud.githubusercontent.com/assets/7060510/8589869/dfc0127c-2655-11e5-88c0-c8ea75ba2a69.PNG)

3. web.xml에 캐릭터인코딩 뒤에 filter 넣기 
![lucy 2](https://cloud.githubusercontent.com/assets/7060510/8589880/03bf2b9a-2656-11e5-858d-564d368e5cd3.PNG)

그리고 한글입력 테스트를 하는데 한글이 깨집니다. 
![default](https://cloud.githubusercontent.com/assets/7060510/8589900/2e578bae-2656-11e5-97c4-654132c92451.PNG)
![default](https://cloud.githubusercontent.com/assets/7060510/8589901/2e6a0a5e-2656-11e5-94f2-c9a4f79124bb.PNG)

그래서 제가 lucy-xss-servlet-filter-rule.xml에 

![conf](https://cloud.githubusercontent.com/assets/7060510/8590029/539b5584-2657-11e5-9ff3-1e406cd56e8b.PNG)

이렇게 입력으로 들어오는 courseF를 필터안하게 설정해봤는데 딱히 해결되진 않더라구요
(저 courseF는 <form:form>을 통해 Spring에서 자동으로 넣어주는 커맨드객체인데 그래서 그런가 지금 막 생각이나서 적어봅니다) 

web.xml  전문

<?xml version="1.0" encoding="utf-8"?>
<web-app version="3.0"
         xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
         http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">

	<display-name>Spring MVC Application</display-name>

    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            /WEB-INF/spring/root-context.xml
            /WEB-INF/spring/dbpool-context.xml
        </param-value>
    </context-param>

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>

    <servlet>
        <servlet-name>appServlet</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>

        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>
                /WEB-INF/spring/appServlet/servlet-context.xml
            </param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>

        <multipart-config>
            <max-file-size>52428800</max-file-size>
            <max-request-size>52428800</max-request-size>
            <file-size-threshold>0</file-size-threshold>
        </multipart-config>
    </servlet>

    <servlet-mapping>
        <servlet-name>appServlet</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>

    <description>MySQL Test App</description>
    <resource-ref>
        <description>DB Connection</description>
        <res-ref-name>jdbc/TestDB</res-ref-name>
        <res-type>javax.sql.DataSource</res-type>
        <res-auth>Container</res-auth>
    </resource-ref>

    
    <filter>
        <filter-name>encodingFilter</filter-name>
        <filter-class>
            org.springframework.web.filter.CharacterEncodingFilter
        </filter-class>
        <init-param>
            <param-name>encodingFilter</param-name>
            <param-value>UTF-8</param-value>
        </init-param>
        <init-param>
            <param-name>forceEncoding</param-name>
            <param-value>true</param-value>
        </init-param>
    </filter>

    <filter-mapping>
        <filter-name>encodingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

    
    <filter>
        <filter-name>xssEscapeServletFilter</filter-name>
        <filter-class>com.navercorp.lucy.security.xss.servletfilter.XssEscapeServletFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>xssEscapeServletFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
    
    <session-config>
        <session-timeout>360</session-timeout>
    </session-config>
</web-app>

lucy-xss-servlet-filter-rule.xml 전문

<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://www.navercorp.com/lucy-xss-servlet">
    <defenders>
        
        <defender>
            <name>xssPreventerDefender</name>
            <class>com.navercorp.lucy.security.xss.servletfilter.defender.XssPreventerDefender</class>
        </defender>

        
        <defender>
            <name>xssSaxFilterDefender</name>
            <class>com.navercorp.lucy.security.xss.servletfilter.defender.XssSaxFilterDefender</class>
            <init-param>
                <param-value>lucy-xss-sax.xml</param-value>   
                <param-value>false</param-value>        
            </init-param>
        </defender>

        
        <defender>
            <name>xssFilterDefender</name>
            <class>com.navercorp.lucy.security.xss.servletfilter.defender.XssFilterDefender</class>
            <init-param>
                <param-value>lucy-xss.xml</param-value>    
                <param-value>false</param-value>         
            </init-param>
        </defender>
    </defenders>

    
    <default>
        <defender>xssPreventerDefender</defender>
    </default>

    
    <global>
        
        <params>
            <param name="globalParameter" useDefender="false" />
            <param name="globalPrefixParameter1" usePrefix="true" useDefender="false" />

            <param name="courseF" usePrefix="true" useDefender="false" />

            
        </params>
    </global>

    
    <url-rule-set>

        
        

        

        

        

        <url-rule>
            <url disable="true">/disableUrl3.do</url>
            <params>
                <param name="query" useDefender="false" />
                <param name="prefix1" usePrefix="true" />
                <param name="prefix2" usePrefix="false" useDefender="false" />
                <param name="prefix3" usePrefix="true" useDefender="true" />
                <param name="prefix4" usePrefix="true" useDefender="false" />
                <param name="prefix5" usePrefix="false" useDefender="true" />
            </params>
        </url-rule>

        
        <url-rule>
            <url disable="false">/disableUrl4.do</url>
            <params>
                
                <param name="query" useDefender="false" />
                <param name="prefix1" usePrefix="true" />
                <param name="prefix2" usePrefix="false" useDefender="false" />
                <param name="prefix3" usePrefix="true" useDefender="true" />
                <param name="prefix4" usePrefix="true" useDefender="false" />
                <param name="prefix5" usePrefix="false" useDefender="true" />
                <param name="prefix6" usePrefix="true">
                    <defender>xssSaxFilterDefender</defender>
                </param>
            </params>
        </url-rule>

        
        <url-rule>
            <url>/url1.do</url>
            <params>
                <param name="url1Parameter" useDefender="false" />
                <param name="url1PrefixParameter" usePrefix="true" useDefender="false" />
                <param name="globalParameter"/>
            </params>
        </url-rule>

        
        <url-rule>
            <url>/url2.do</url>
            <params>
                <param name="url2Parameter1" useDefender="false">
                    <defender>xssPreventerDefender</defender>
                </param>
                <param name="url2Parameter2">
                    <defender>xssSaxFilterDefender</defender>
                </param>
                <param name="url2Parameter3">
                    <defender>xssPreventerDefender</defender>
                </param>
            </params>
        </url-rule>
    </url-rule-set>
</config>

**Comment by leeplay** [comment]
안녕하세요 
자세한 정보 감사합니다. ~ 

일단 이런 유사한 문제는 기존에도 많은 문의가 있었습니다. 
대부분 라이브러리 의존성 문제 or 필터 선언 순서 문제였습니다.

알려주신 정보로 보면 설정은 이상한 점은 없는 거 같습니다. 
그런데 필터링 제외 설정을 하셨는데 필터링이 된다는게 좀 의아스럽네요 

문제의 범위를 좁혀보기 위해서 
현재 개발하시는 프로젝트에서 junit으로 아래와 코드를 돌려주실 수 있을까요 ???

```
@Test
public void testXssPreventer() {
    String dirty = "\"><script>alert('한글');</script>";
    String clean = XssPreventer.escape(dirty);

```

이 테스트에서 한글이 깨지면 메이븐 디펜던시 설정을 확인해볼거구요 
한글이 깨지지 않으면 서블릿 단을 의심 해보려 합니다. 

감사합니다.

**Comment by yangbongsoo** [comment]
Junit을 통해서 돌려본 결과입니다 !! 
![default](https://cloud.githubusercontent.com/assets/7060510/8612630/7e9e664c-270e-11e5-834a-cbe9ef29007b.PNG)

**Comment by leeplay** [comment]
추가 정보 감사합니다. 
라이브러리를 직접사용했을 때 한글이 깨지지 않을걸로 보아 테스트 결과를 보니 라이브러리는 정상적으로 보입니다. 

그럼 이번엔 제가 yangbongsoo님이 주신 설정 정보로 저도 테스트를 해봤습니다. 

- web.xml 설정 

![1](https://cloud.githubusercontent.com/assets/7857613/8613792/c12e5cec-271d-11e5-8574-5069806c494d.PNG)

- lucy-xss-servlet-filter-rule.xml 설정

![2](https://cloud.githubusercontent.com/assets/7857613/8613812/0fcff590-271e-11e5-8560-3a0aa7a6a6c6.PNG)

- 한글 데이터 입력

![3](https://cloud.githubusercontent.com/assets/7857613/8613832/37f0e390-271e-11e5-915b-cbb4c411b8f3.PNG)

- 서버 내 디버깅

![4](https://cloud.githubusercontent.com/assets/7857613/8613844/5fba13e2-271e-11e5-81e6-ba4684768402.PNG)

위의 디버깅 화면을 보시면 설정을 동일하게 하고 필터링 수행 후  리턴하는 한글 값이 깨지지 않은 걸 확인할 수 있습니다. 

그럼 이번엔 yangbongsoo님이 제가 디버깅 위치를 찍은 지점에  doFilter 를 수행하기 전의 value값과 수행 후 value 값을 디버깅으로 확인해주실 수 있으신가요 ?

lucy-xss-servlet-filter와 lucy-xss-filter의 소스 파일은 메이븐 센트럴에 전부 업로드 되어 있습니다. 
pom.xml에 아래처럼 선언해주시고

```
               <dependency>
   			 <groupId>com.navercorp.lucy</groupId>
    		         <artifactId>lucy-xss-servlet</artifactId>
   			 <version>2.0.0</version>
   			 <classifier>sources</classifier>  
		</dependency>
		
 		<dependency>
			<groupId>com.navercorp.lucy</groupId>
			<artifactId>lucy-xss</artifactId>
			<version>1.6.3</version>
			<classifier>sources</classifier>
		</dependency>
```

브레이크 포인트 위치는 XssEscapeServletFilterWrapper 의  getParameter 관련 메소드 입니다.

**Comment by leeplay** [comment]
디버깅 포인트에서 필터링 메소드 전후의 값을 비교 후 필터링 후에 깨지게 되면 현재 프로젝트의 apache-common-lang 라이브러리의 버전을 의심해봐야 할 거 같구요 원래부터 깨진 상태로 들어오면 필터간 우선순위를 변경해야 할 거 같습니다. (처음에 이걸 의심했는데 ... 주신 설정에선 특별한게 보이지가 않네요 ;;)

추가로 알려주신 정보로 좀 더 파보도록 하겠습니다. ~

**Comment by yangbongsoo** [comment]
1. Debugging 이슈 
제가 XssEscapeServletFilterWrapper 에서 BreakPoint를 찍었는데 수정이 안되는 외부 class파일에 
디버깅이 되는지 잘 몰라서요 ㅠㅠㅠㅠ 어떤식으로 해야할지 ... 
![classfile](https://cloud.githubusercontent.com/assets/7060510/8614673/fc6db218-2726-11e5-89e0-1dfdea115acf.PNG)

2. 제가 pom.xml을 뒤져봤는데 common-lang 라이브러리를 추가하지는 않았습니다. 

3. 필터간 우선순위라는게 web.xml 설정 말씀하시는게 맞나요? 제가 설정한 필터는 캐릭터셋 하나인데
캐릭터셋 뒤에 와야 한다고 알고 있습니다. 추가적으로 캐릭터셋 앞에서 돌려보고 뒤에서도 돌려봤지만 
결과는 계속 깨지는 현상이 발생합니다. ㅠㅠ

**Comment by yangbongsoo** [comment]
제가 계속 이런저런 테스트를 해봤는데 한글인코딩이 깨지는건지 아니면 한글자체를 &euml;&sect;�&euml;&deg;�&igrave;�&not; 이런식으로 바꾸는건지 잘 모르겠습니다.

만약 한글자체를 임의로 바꾸는거라면 어떤식으로 막을 수 있을까요?

**Comment by leeplay** [comment]
만약 한글자체를 임의로 바꾸는거라면 어떤식으로 막을 수 있을까요? 
-> 어디서 변경되는지 확인이 힘든 상황에서 이 질문에 대한 답을 못할 것 같습니다. ^^;;; 

더 위에 적어주신 글에 답변을 하도록 하겠습니다. ~

1. class 파일도 디버깅 가능합니다. 
지금 class 파일에 브레이크 포인트 찍으신 다음에 이벤트 발생하시면 해당 소스로 이동할겁니다. 
만약 소스를 못 찾아서 사용하시는 인텔리제이에서 소스 위치를 알려달라는 창이 뜨면 .m2/repository/com/navercorp/lucy/lucy-xss-servlet/2.0.0 로 이동하셔서 lucy-xss-servlet-2.0.0-sources.jar 파일을 선택하시면 됩니다.  그러면 일반 디버깅 하는 것처럼 동일하게 작동합니다. 

처음부터 브레이크 포인트 찍진 마시고 한글 데이터 입력 이벤트 전에 찍으시고 하시면 원하는 상황에 좀 더 수월하게 도달할 수 있습니다. 

2. pom.xml  에 직접 추가하진 않으셔도 여러 라이브러리에서 common-lang을 가져다 쓸 가능성이 있으니 언급을 드렸습니다.  (충돌 가능성이 낮긴 합니다.) 혹시 모르니 mvn dependency:tree 수행 후 결과를 보여주시겠어요 ?
아래같은 겁니다. 

![1](https://cloud.githubusercontent.com/assets/7857613/8632213/a1a40e1c-27cc-11e5-9e90-2a8c049e338b.PNG)

3. 잘 해보신 것 같습니다. 현재 설정하신 위치가 맞습니다. 이것도 혹시 몰라서 언급을 드린 거였습니다. 

현재 상황을 한번 더 정리해보면 저의 프로젝트와 yangbongsoo 님의 프로젝트에 web.xml, lucy 설정 파일을 동일하게 하고 한글 데이터 입력 시 서로 다른 필터링 결과를 보여주고 있습니다. 어플리케이션 내의 설정이 동일하니 개발환경 서버 쪽의 설정을 확인해봐야 하나라는 생각이 듭니다. ;;;

제가 한번 더 요청을 드리는 사항은 3가지 입니다. 

- 가장 확실한 건 디버깅으로 필터 수행 전 후 간에 입출력값의 변화를 보는 게 가장 좋으니 가능하시면 디버깅 방법을 한번 주위 분들에게 물어보셔서 한번 해주셨으면 좋겠습니다. 

- junit 테스트 코드는 현재 문제가 발생 중인 프로젝트안에서 작성하신 게 맞죠 ?

- 현재 프로젝트를 저에게 보내주실 수 있으신가요 ?

**Comment by yangbongsoo** [comment]
메일로 프로젝트 파일을 보냈습니다 !! 
![xss 1](https://cloud.githubusercontent.com/assets/7060510/8707109/bf0be2b8-2b6e-11e5-9d9d-ed7473f450bf.PNG)
![2](https://cloud.githubusercontent.com/assets/7060510/8707110/bf0f16d6-2b6e-11e5-9049-a7ccb9964c81.PNG)

간단하게 로컬에서 입력받았을때 서버에서 system.out.println으로 깨지는 것을 확인할 수 있습니다

**Comment by leeplay** [comment]
넵 제가 디버깅 해보고 연락드리겠습니다.

**Comment by leeplay** [comment]
디버깅 해봤습니다. 

결론은 lucy-xss-servlet-filter와는 상관없는 오류였습니다. ^^;;;
디버깅을 해보니 이미 "ServletModelAttributeMethodProcessor" 부분에서 한글 데이터가 깨진 상태로 생성이 되고 lucy-xss-servlet-filter가 받았을 때도 이미 당연히 한글 데이터가 깨져있었습니다. 

제 테스트 스샷입니다. ㅎ ~~~

![2015-07-16 11 36 59](https://cloud.githubusercontent.com/assets/7857613/8714435/ae4b3618-2baf-11e5-83c3-f29c9655e7d1.png)

![2015-07-16 11 37 05](https://cloud.githubusercontent.com/assets/7857613/8714436/b43daf88-2baf-11e5-9d77-9b9965bf6559.png)

해결방법은
library.jsp 에 pageEncodig  선언이 누락되어 있었습니다. 
아래처럼 선언하시면 됩니다. ~ 

```
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
```

**Comment by yangbongsoo** [comment]
지금 <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %> 넣었는데도 제 프로젝트에서는 계속 한글이 깨져서 이유를 찾아보는중입니다. 분명 구글링해서 인코딩하라는건 다했었는데(톰캣 server.xml설정, db.properties설정,mysql안에 utf-8설정 , web.xml 설정) ㅠㅠㅠ 진짜 하라는건 다했는데 
![11](https://cloud.githubusercontent.com/assets/7060510/8716813/99928d00-2bcf-11e5-9a28-1b9e4250c78f.PNG)
![22](https://cloud.githubusercontent.com/assets/7060510/8716815/9d7c9168-2bcf-11e5-9384-ea685b07d097.PNG)

프로젝트 외적인 문제일 수가 있나요? ㅠ

**Comment by yangbongsoo** [comment]
![adsfad](https://cloud.githubusercontent.com/assets/7060510/8716852/f4e47a74-2bcf-11e5-91e4-c5abffbd4415.PNG)
인텔리제이 setting 설정도 utf-8로 해놨었습니다

**Comment by leeplay** [comment]
에디터의 설정은 프로그램 내의 파라메터와는 상관이 없을 거예요 

yangbongsoo 님이 안된다고 하시는 부분은 여기서 제가 확인할 수 있는 방법이 없네요 ;;; 
다 동일하다고는 하시는데 제가  yangbongsoo 님이 어떻게 테스트하고 있는지 눈으로 보이는게 아니라서 ...
( 이 말을 좀 더 구체적으로 하자면 컴파일된 결과물이 잘반영되고 있는지, IDE가 바라보는 톰캣은 문젠가 없는 것인지.. 등등이요)

jsp에 엔코딩 선언을 잘하셨다면 프로젝트에는 문제가 없어보입니다. 

제가 한 것은 yangbongsoo님의 프로젝트를 바로 인텔리제이로 열어서 제 톰캣에 배포한 것 뿐이예요 
일단 원격지에서 확인이 가능한 건 다 했는데요, 프로젝트까지 직접 받아서 테스트 했는데 ...
이 이상은 더 하고 싶어도 할게없네요 ... ㅜ

**Comment by yangbongsoo** [comment]
다음주 월요일날 찾아뵈도 될까요??

**Comment by leeplay** [comment]
네 오후 2시 이후로 괜찮을 것 같습니다.  도착하셔서 댓글 주시면 될 거 같습니다.

**Comment by yangbongsoo** [comment]
넵 월요일날 분당 정자동 그린팩토리로 갈께요 !!

**Comment by leeplay** [comment]
오셨으면 댓글 하나 달아주세요 ~

**Comment by yangbongsoo** [comment]
저 방금 1층 도착했습니다!

**Comment by leeplay** [comment]
해당 이슈는 잘 마무리되었습니다. ^^ 
 yangbongsoo 님 기념으로 찍어가신 사진 여기올리셔도 재밌을 거 같습니다. ㅎ

**Comment by yangbongsoo** [comment]
![20150720_150120](https://cloud.githubusercontent.com/assets/7060510/8775362/5be95b04-2f22-11e5-97df-d4516fe4fad8.jpg)
![20150720_163120](https://cloud.githubusercontent.com/assets/7060510/8775363/5bf52c72-2f22-11e5-9e57-cd5266899f12.jpg)
![20150720_163239](https://cloud.githubusercontent.com/assets/7060510/8775364/5bfdd714-2f22-11e5-913d-27eda4118d31.jpg)
회사 업무로 많이 바쁘실텐데 이렇게 자기일처럼 도와주셔서 감동이었습니다  다시 한번 감사드리며 오픈소스 활동 열심히 하겠습니다 !!

**Comment by leeplay** [comment]
넵 오픈소스 활동을 하시겠다니 좋네요
앞으로도 네이버 오픈소스 많은 관심 부탁드립니다 
먼 길 오시느라 수고하셨습니다 ~~~

**Comment by nstopkimsk** [comment]
오!! 멋지네요.

**Comment by TaeSeong** [comment]
와 훈훈합니다. :+1:

**Comment by bennyrick** [comment]
지린다

**Comment by hellobk1231** [comment]
댓글 남기려 로그인했어요 와 정말 훈훈하네요 ㄹㅇ리스펙
