### ISSUE TITLE
defender 의 init-param 과 관련한 문의입니다

### ISSUE THREAD

**Issue by BradKim** [naver/lucy-xss-servlet-filter#22]
lucy-xss-servlet-filter 적용 중 궁금한 부분이 있어 문의 드립니다.

제목처럼 lucy-xss-servlet-filter-rule.xml 에 작성해야 하는 defender 설정 중, <init-param>과 관련된 내용입니다.

적용 및 테스트중인 defender 는 "XssSaxFilterDefender" 이며, 매뉴얼에 기술된 대로 <init-param>의 두번째 인자에는 false를 적용하였습니다. (성능 향상을 고려하여)
```XML
...
<!-- XssSaxFilter 등록 -->
<defender>
  <name>xssSaxFilterDefender</name>
  <class>com.navercorp.lucy.security.xss.servletfilter.defender.XssSaxFilterDefender</class>
  <init-param>
    <param-value>lucy-xss-sax.xml</param-value>
    <param-value>false</param-value><!-- 필터링된 코멘트 기록. 성능을 위해서는 false 설정하는 것이 맞음. -->
  </init-param>
</defender>
...
```

제가 처음에 이해한 바로는,
> false 로 설정할 경우 "필터링 코멘트를 남기지 않으며, 이로인해 성능 향상에 조금더 도움이 된다" 였고,
> true 로 설정할 경우 "필터링 코멘트를 남기므로, 어느정도 리소스를 소모한다" 였습니다.

하지만, 테스트 과정에서는 기대했던 것과는 달리 반대의 결과를 확인 할 수 있었으며, 정확한 의미 파악을 위해서 소스코드를 분석해보던중 위의 두번째 인자인 boolean 값의 변수명이 **withoutComment** 라는 것을 알게 되었습니다.

아래 코드는 lucy-xss-filter 의 XssSaxFilter.java 입니다.
```JAVA
...
public static XssSaxFilter getInstance(String fileName, boolean withoutComment) throws XssFilterException {
    try {
        synchronized (XssSaxFilter.class) {
            ...
            this.withoutComment = withoutComment;
            ...
        }
    }
}
...
```
변수명으로 추정했을 때 **withoutComment** 는 true 일 경우 코멘트를 남기지 않으며, false 일 경우 코멘트를 남긴다는 의미로 쓰일 것 같은데, 제가 생각하고 있는 것이 맞을지요?

사내 공통 적용을 위해 가이드 문서를 작성하려고 보니 의미 전달이 정확해야 할 것 같아서, 확인차 문의 드립니다.

감사합니다.

**Comment by leeplay** [comment]
확인해보니 이해하신 대로 코드가 동작하니 
lucy-xss-servlet-filter-rule.xml 의 문서 설명이 잘못된 걸로 보여요 

xss-filter의 테스트 케이스도 그렇게 작성되어 있네요 :)

**Comment by BradKim** [comment]
확인 및 답변 감사드립니다.
이제 정확히 알게 되었네요. ^^
