### ISSUE TITLE
object 태그에 param 이 추가되지 않도록 할 수 있나요?

### ISSUE THREAD

**Issue by BradKim** [naver/lucy-xss-servlet-filter#23]
XssSaxFilter 를 적용하여 사용 중입니다.

object 태그 처리와 관련한 문의인데요.

obejct  태그를 허용하기 위해 element rule을 아래와 같이 설정했습니다.
`<element name="object" extends="true" disable="false" removeTag="false"/>`

다만, object 태그가 필터를 거치면 여러가지 param 태그가 자동으로 추가되고 있는데, 이 param 들이 추가되지 않도록 설정에서 제어 할 수 있을지요?

설정으로 안된다면 Listener 를 따로 구현해야 한다던가 혹은 다른 방법이 있을지 궁금합니다.

(원래 lucy-xss-filter project 에 문의했었는데, 한동안 답이 없어 혹시 몰라서 이곳에도 올리게 되었습니다)

**Comment by leeplay** [comment]
안녕하세요
설정 혹은 리스너로 대응이 되나 확인해봤는데 안되네요 

이 룰은 네이버에서 정한 룰인데요
(https://github.com/naver/lucy-xss-filter/blob/master/docs/manual/kr/03.%20usage%20guide/3.4%20Using%20the%20ElementListener.md)

XssSaxFilter.doObjectEndTagProcess 메소드 내에서 설정하지 않은 보안 파라미터를 자동으로 추가합니다.
정의된 파라미터는 리스너를 등록할 수 없으므로 리스너 추가로 해당 값들을 제거시킬 수 없네요 

white-url로 등록해도 뒤의 파라미터는 추가됩니다. (강력한 보안의 이유로요)

@BradKim 님이 당장 시도해볼 수 있는 방법은 죄송스럽지만 소스코드를 직접 빌드해 사용하셔야 할 거 같은데요, XssSaxFilter 내에 아래 584라인의 if문을 주석처리 하시면 됩니다. (존재하지 않은 파라미터의 추가이니 제거하셔도 기능상으로는 무리 없어보입니다.)

<img width="1277" alt="2018-02-27 19 38 12" src="https://user-images.githubusercontent.com/7857613/36724197-c7876f6e-1bf5-11e8-90d1-3a387ce27917.png">


@benelog 님 

(위의 방법말고 더 좋은 해결책이 있을지 떠오르지 않아요 ;;)
object 태그의 현행 방식에 대해 고민이 필요해 보여요 

XssSaxFilter가 object 태그에 대해 작동 시 
white-url에 한 해 후속처리 작업 없이 바로 리턴시키거나 보안 파라미터를 추가할 경우 설정.xml 파일에 리스너를 등록시켜서 개발자가 원하는 작업을 할 수 있도록 하는 기능제공?을 할 수 있을 거 같아요 (전자가 깔끔하겠네요)

**Comment by BradKim** [comment]
@leeplay 님, 답변 감사드립니다.

답변 기다리는 동안 XssSaxFilter 의 소스코드를 살펴보고 있었는데, 말씀하신대로 doObjectEndTagProcess  메소드 내에서 문제의(?) param 을 추가하는 것을 확인 할 수 있었습니다.

결국, 저 부분을 주석 처리하고 직접 소스 빌드를 하는 것으로 답이 나오네요.

그래서, 추가로 한가지만 더 질문 드리고 싶은데요.
아래와 같이 소스코드를 운용해도 문제가 없을지 체크만 부탁드리고 싶습니다.
(주로 라이선스 문제겠네요)

- 소스코드를 사내 전용 git repository 에서 버전 관리 (회사에서 운영사는 서비스에만 적용됩니다)
- 현재 Maven 기반의 프로젝트를 Gradle 기반으로 변경
- Language level 을 1.5 에서 1.8 로 변경

이정도로 운용해도 문제 없을지요?

Lucy 덕분에 엄청난(?) 분량의 보안 요구사항을 다 해소할 수 있어서 너무 감사하게 쓰고 있습니다. :-)

**Comment by leeplay** [comment]
@BradKim 

큰 문제 없어보이는데 사내 라이선스 담당자 분께 확인해 볼게요 
도움이 되셨다니 다행입니다. :)

**Comment by benelog** [comment]
@BradKim 
담당자로부터 아래와 같은 답변을 받았습니다.

>lucy-xss-servlet-filter는 Apache Lincense v2로 배포되고 있으므로, 해당 라이선스 조항에 위배되지 않으면 회사에서도 자유롭게 사용할 수 있습니다. 
>
>라이선스에 대한 상세 내용은 아래 링크를 참고하시길 부탁드립니다.
>
> https://naver.github.io/OpenSourceGuide/book/UsingOss/the-legal-side-of-opensource.html#licensedef

**Comment by BradKim** [comment]
답변 감사드립니다.
보내주신 내용 숙지하고, 라이선스 조항을 준수하여 운용하도록 하겠습니다. :-)
