### ISSUE TITLE
제 프로젝트에서 안됐던 문제에 대해 정리해봤는데 맞는지 궁금합니다

### ISSUE THREAD

**Issue by yangbongsoo** [naver/lucy-xss-servlet-filter#3]
![default](https://cloud.githubusercontent.com/assets/7060510/8781689/94b3a61e-2f4b-11e5-9d98-b061a767cf69.PNG)
문제가 해결되면서 설명해주셨던 내용을 정리해봤는데 제가 제대로 이해했나요? 

추가적으로 JSP 캐릭터셋 우선순위에 관련해서 책을 찾아봤는데  
'web.xml의 인코딩 설정을 읽은 후 pageEncoding을 찾는다' 라고 되어 있더라구요.
즉, 제 프로젝트에서는 
1. web.xml인코딩 설정에 오류가 있으니까 적용이 안됌
2. 그래서 pageEncoding을 찾아가지만 이미 그전에 web.xml에 설정된 lucy-xss-servlet-filter가 적용되서 문자열 처리됨
3. 그러므로 각각의 JSP 파일에 pageEncoding="utf-8"해도 소용이 없음
이렇게 된게 맞나요?

**Comment by leeplay** [comment]
네 맞습니다. 
참고로  lucy는 html entity encoding 규칙에 따라 수행을 하고 이 규칙은 lucy 가 정한 건 아니예요 (전세계 공통입니다.) 규칙에 따라 동작을 했기 때문에 lucy에서 꼬였다라고는 볼 수 없을거 같아요, 그런 문자열로 만든 쪽 문제니까요 ^^
