### ISSUE TITLE
content에 form 검사는 안되나요?

### ISSUE THREAD

**Issue by legshort** [naver/lucy-xss-servlet-filter#4]
테스트 돌려보니 설명처럼 request에 getParam* 호출될때만 filter가 작동 되므로 contents에 form을 넣어서 테스트 해 보니 trigger 되지 않는거 같습니다.

form 검사는 현재 사용 불가 인가요?

**Comment by leeplay** [comment]
좀 더 자세히 설명해주실 수 있으실까요 ???

**Comment by legshort** [comment]
하하 ^^;;;;; 적고 보니 제 입장에서 질문을 했네요.

기본적으로는 REST + JSON 방식으로 개발 환경입니다. (스프링 블로그: https://goo.gl/I9zcrg)
POST로 JSON 포맷을 서버에 요청하며 Form에서 사용되는 Field들도 XSS 필터링 지원 되는지 궁금합니다.

실제 자바 파일 하단에 링크에 있습니다.

Form.java: https://goo.gl/qk2PSq
Controller: https://goo.gl/tZxJs5
Test: https://goo.gl/PCO8Lw

**Comment by leeplay** [comment]
"POST로 JSON 포맷을 서버에 요청하며 Form에서 사용되는 Field들도 XSS 필터링 지원 되는지 궁금합니다."

getParam 주석을 확인해보니 아래의 경우에 작동한다고 하는 걸로 봐서 사용 중인 케이스에는 작동을 안할 거 같습니다. (parameters are contained in the query string or posted form data.) 

말씀하신 대로  getParam이 호출될 때만 작동을 합니다. 원하시는 트리거를 일으키시려면 json이 아닌 form타입으로 전송하셔야 할 겁니다. ~  

전송 타입의 변경이 불가하시고  @RequstBody를 사용해야한다면 서비스 레이어로 가기 전에 직접 XssPreventer나 XssSaxFilter의 필터링 메소드를 호출하시는게 깔끔한 방법일 거 같습니다. ~  
(lucy-xss-servlet-filter는 lucy-xss-filter를 자동으로 사용하기 위해 서블릿으로 랩핑했기 때문에 직접 메소드를 호출하셔도 상관없습니다. ^^)

**Comment by legshort** [comment]
네 감사합니다~ 저도 생각해 보니 json 방식이랑 다른거 같더라구요. 지금은 angular 연동이라서 view 레이어가 xss 처리하는 방식으로 갈거 같은데 개인적으로는 원천적으로 db 저장시에도 escape해야된다고 생각했던거라 annotation으로 luxy호출하는 방식을 생각하고 있습니다. Rest 기반 security를 좀 더 봐야겠습니다. 기회가 된다면 json 방식 form에서 적용가능한 annotation 만들어서 pr 날리도록 하겠습니다!

**Comment by leeplay** [comment]
방향을 아주 잘 잡으신 거 같습니다. ~  
pr까지 날려주시면 정말정말 감사하게 생각하겠습니다. ^^

**Comment by benelog** [comment]
JSON 내부의 문자열을 치환하는 역할을 ServletFilter에서 하기에는 몇가지 걸리는 점이 있습니다. 속성명에 따라서 따라 제외/추가 규칙을 넣으려면 결국 Filter에서 JSON을 파싱해야 합니다. 그런데 ServletFilter의 뒷단에서 파싱을 한번더 하게된다면 중복파싱이 되어서 효율적인 구조가 되지 못합니다. 그리고 특정 Json 파싱 라이브러리에 대한 의존성이 생기는 부담도 생깁니다.

JSON에 대한 ecape처리는 ServletFilter보다는 다른 레이어에서 해주는것이 더 적절하지 않을까하는 생각이 듭니다. http://homoefficio.github.io/2016/11/21/Spring%EC%97%90%EC%84%9C-JSON%EC%97%90-XSS-%EB%B0%A9%EC%A7%80-%EC%B2%98%EB%A6%AC-%ED%95%98%EA%B8%B0/ 이 좋은 예가 될것 같습니다.

ServletFilter에서 하게 된다면, 정교한 규칙없이 'application/json'으로 요청이 들어올때 request body를 전체를 치환하는 기능정도를 고려해볼만할것 같습니다.
