### ISSUE TITLE
lucy 필터를 적용하려고 합니다.

### ISSUE THREAD

**Issue by yoonsooyoung** [naver/lucy-xss-servlet-filter#6]
완료된 프로젝트에 보안취약점 진단 후 lucy 필터를 적용하려고 합니다.
프로젝트 내에서 데이터 처리를 주로 json으로 처리하였는데
lucy 필터를 적용 후 ' " ' (double quotation) 때문에 정상적인 데이터 처리가 되지 않습니다.
그래서 lucy 필터에서 double quotation만 제외하려고 하는데 어떻게 처리를 해야될지 모르겠어서 문의드립니다.
적용하려는 버전은
lucy-xss-servlet-2.0.0 과 lucy-xss-1.6.3 입니다.

**Comment by leeplay** [comment]
안녕하세요 
휴가 중이여서 답변이 늦었습니다. ^^;;;

먼저 lucy-xss-filter의 주 필터링 대상은 html 입니다. 
html 중 사용자가 필터링 하고 싶은 태그들을 제거하면서 안전한 html만 유지해주는 라이브러리 입니다. (주로 html 입력을 허용하는 게시판이나 메일같은 서비스라고 볼 수 있습니다.)
여기에 html 태그를 유지하지 않고 일괄적으로 xss 공격을 필터링 하는 기능을 추가제공 하고 있습니다.
아마 후자 기능을 사용하실 거 같은데요 (XssPreventer를 사용하시는 기준으로 생각하겠습니다.)

lucy-xss-servlet-filter는 일반적인 서블릿 필터입니다.  
getParameter를 수행할 때 (json파싱이 일어나기 전) xss 공격요소에 대해 필터링을 하게 됩니다.
"" 이게 json 규약인 줄 모르고 문자열의 일부라고 인지해서 필터링 대상이 아닌데
필터링이 될 거 같고 윤수영님이 말씀하시는 비정상 케이스가 될 거 같습니다.

현재 상황에서 해결책으로는 아래 두가지가 있을 거 같은데요 
1번을 추천드립니다. 

1. servlet-filter를 사용하지 않고 lucy-xss-filter만 사용해서 json 파싱이 끝난 후 직접 필터링 메소드를 호출한다. 
2. 오로지 json데이터만 들어온다면 servlet-filter에 컨텐츠 타입이 json일 경우엔 "" 를 escape하지 않도록 소스를 수정한다.
