### ISSUE TITLE
@Configuration으로 설정시

### ISSUE THREAD

**Issue by nuxer75** [naver/lucy-xss-servlet-filter#8]
AbstractAnnotationConfigDispatcherServletInitializer 을 상속받아 SpringWebMvcInitializer 를 구현하였습니다.
getServletFilters를 override하지 않고 onStartup을 override 하여 다음과 같이 세팅하였습니다.

@Override
    public void onStartup(ServletContext servletContext) throws ServletException {

        super.onStartup(servletContext);
        FilterRegistration.Dynamic encodingFilter = servletContext.addFilter("encodingFilter", new CharacterEncodingFilter());
        encodingFilter.setInitParameter("encoding", "UTF-8");
        encodingFilter.setInitParameter("forceEncoding", "true");
        encodingFilter.addMappingForUrlPatterns(null, true, "/*");

        FilterRegistration.Dynamic xssEscapeServletFilter = servletContext.addFilter("xssEscapeServletFilter", new XssEscapeServletFilter() );
        xssEscapeServletFilter.addMappingForUrlPatterns(null, true, "/*");
    }

resources 폴더 아래에 lucy-xss-servlet-filter-rule.xml 을 설정하였고 lucy-xss-sax.xml 파일도 정의하였습니다.

url 을 호출하면 XssEscapeServletFilter 로 진입하여 doFilter 를 호출하는데

@Override
public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
	chain.doFilter(new XssEscapeServletFilterWrapper(request, xssEscapeFilter), response);
}
메소드에서 
new XssEscapeServletFilterWrapper(request, xssEscapeFilter) 를 실행하고 그냥 종료해버립니다.

XssEscapeServletFilterWrapper의 doFilter 를 호출하지 않는데 왜그런지 알수 있을까요?

**Comment by leeplay** [comment]
doFilter까지 진입을 했다고 하시니 다음 연속된 메소드가 호출이 안될 거 같진 않은데 XssEscapeServletFilterWrapper의 getParameter에 브레이크 포인트 찍어보고 진입이 안되는지 확인해 볼 수 있을까요 ? 

```
public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
chain.doFilter(new XssEscapeServletFilterWrapper(request, xssEscapeFilter), response);
}
```

혹시 모르니 아래 링크에서 getParameter가 불려지는 케이스와도 동일한지 확인 한 번 해주세요 
https://github.com/naver/lucy-xss-servlet-filter/issues/4

여기까지 확인후 안되시면 구현하신 코드와 테스트 코드 올려주시면 저도 한번 테스트 해보겠습니다. 
감사합니다.

**Comment by nuxer75** [comment]
죄송요.. 테스트에서 실수했습니다. 정상적으로 동작합니다. ^^;
