### ISSUE TITLE
lucy-xss-servlet-filter 적용에 대해 질문드립니다.

### ISSUE THREAD

**Issue by EUWOOZIK** [naver/lucy-xss-servlet-filter#9]
XSS 관련해서 현재 완료된 프로젝트에 보안취약점 해결을 위해서 lucy-xss-servlet-filter를 적용하려 합니다.

가이드를 읽고 설치를 했는데 몇가지 의문점이 남아서 질문드립니다.

(일단 Library에 lucy가 설치 되있는것은 확인) 

1. lucy-xss-filter 도 설정해줘야 하는지 궁금합니다.
 ( lucy-xss-superset.xml , lucy-xss-superset-sax.xml , white-url.xml  의 작성)
2. 만약 따로 lucy-xss-filter 을 따로 설정하지 않는다면 패턴 조절은 어디서 해야할까요 ?

**Comment by leeplay** [comment]
안녕하세요 
xss-filter 개발자 이형규 입니다. ^^

1번 질문에 답은 lucy-xss-filter도 설정하셔야 합니다. (그러니 2번 질문은 스킵할게요 )
 lucy-xss-servlet-filter-rule.xml 파일 안에 보시면 아래처럼 lucy-xss-filter용 설정파일을 바라보게 되어 있습니다. 사용하시려는 필터에 따라서 선언하시면 될 거 같습니다.

``` XML
<defender>
           <name>xssSaxFilterDefender</name>
           <class>com.navercorp.lucy.security.xss.servletfilter.defender.XssSaxFilterDefender</class>
           <init-param>
               <param-value>lucy-xss-sax.xml</param-value>   <!-- lucy-xss-filter의 sax용 설정파일 -->
               <param-value>false</param-value>        <!-- 필터링된 코멘트를 남길지 여부, 성능 효율상 false 추천 -->
           </init-param>
       </defender>

```

lucy-xss-superset.xml , lucy-xss-superset-sax.xml  처음부터 설정하실 필요없구요 
디폴트로 사용하시다가  디폴트 정책이나 공통으로 빼두고 싶은 설정이 있으시다면 그 때 수정하시면 될 거 같습니다. 
프로젝트별 설정은 위의 설정파일이 아닌 lucy-xss-sax.xml or lucy-xss.xml 이 프로젝트별 설정입니다.

헷갈리실거 같으니 단계별로 접근하자면 
아래 링크 참고하셔서 lucy-xss-filter가 설정한대로 잘 작동 중인지 테스트해보시고요

https://github.com/naver/lucy-xss-filter/blob/master/docs/manual/kr/04.%20quick%20guide/4.1%20Quick%20Start%20guide.md

이 과정이 끝나면 lucy-xss-servlet-filter로 필터선언 했을 때 filter단에서 설정하신 필터로 필터링 되는지 확인하시면 됩니다. (실제 일은 lucy-xss-filter가 합니다. lucy-xss-servlet-filter는 필터메소드 호출을 자동화 해주는 역할입니다.)

감사합니다.
